version: "3"
services:

    redis:
        image: redis
        hostname: redis
        ports:
            - "6380:6379"
        volumes:
            - "redis_data:/data"
        networks:
            - databases

    psql:
        image: postgres:12
        hostname: postgres
        env:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - "postgres_data:/var/lib/postgresql/data/"
        ports:
            - "5434:5432"
        restart: unless-stopped
        networks:
            - databases

networks:
  databases:
    name: databases
    driver: overlay
    attachable: true

volumes:
    redis_data:
    postgres_data: