service: discord
type: Send discord message
image: hawwwdi/send-discord-message
fields:
    - key: TEXT
      type: text
    - key: WEBHOOK_URL
      type: text
author: hawwwdi
icon: https://www.svgrepo.com/show/353655/discord-icon.svg
node_color: 5865F2
description: Sends discord message using discord channel webhook
